### ISSUE TITLE
RxKotlin 3 package name

### ISSUE THREAD

**Issue by mickverm** [ReactiveX/RxKotlin#227] opened 2020-02-15 10:46 UTC
[RxAndroid 3](https://github.com/ReactiveX/RxAndroid) changed its package name to `io.reactivex.rxjava3.android`

Should RxKotlin follow the same naming strategy: `io.reactivex.rxjava3.kotlin`?

**Comment by vpriscan** [comment] 2020-03-11 18:38
It is already changed from io.reactivex.rxkotlin to io.reactivex.rxkotlin3, and my opinion is that changing it again would cause confusion among users (even though it is a RC).

**Comment by lwasyl** [comment] 2020-03-12 10:17
I'd argue for changing the package again, to `io.reactivex.rxjava3.kotlin`, before the final release. For one consistency will help with clarity in the long term, and changing this before the release will only be confusing/an issue for people who updated to an RC version early. But also `io.reactivex.rxkotlin3` suggests compatibility with Kotlin 1.3 and not RxJava3. ~Perhaps with Kotlin 1.4 release there'll be need to have a separate artifact for it, in which case `io.reactivex.rxjava3.kotlin4` would be available. Not sure how likely this scenario is, but anyway~ consistency with other rxjava3 groups feels enough to warrant the change

**Comment by vpriscan** [comment] 2020-03-12 20:25
@lwasyl I don't think package rxkotlin3 suggests Kotlin 1.3. It's not "Kotlin 3". 

But consistency with other RxJava3 namings does provide warranty. 

@thomasnield can you decide?

**Comment by mickverm** [comment] 2020-03-12 20:48
I'd change just for the consistency, it makes RxJava3 feel like a complete ecosystem.

**Comment by lwasyl** [comment] 2020-03-12 21:01
> I don't think package rxkotlin3 suggests Kotlin 1.3. It's not "Kotlin 3".

That was a stretch, I admit :) I just see how version number near `kotlin` instead of `rxjava` might be confusing

**Comment by vpriscan** [comment] 2020-03-12 22:27
You have convinced me that package `io.reactivex.rxjava3.kotlin` is better. Reason is, yes, RxKotlin is just a tiny extension over RxJava, just like RxAndroid is. Having the mentioned package names contributes to the overall feeling that all RxJava ecosystem components are designed to work together hand in hand.
This does look nice:
```
import io.reactivex.rxjava3.flowables...
import io.reactivex.rxjava3.observables...
import io.reactivex.rxjava3.android...
import io.reactivex.rxjava3.kotlin...
```

If RxKotlin is ever rewritten in pure Kotlin, be it for JVM, JS, Native or all of them, then `io.reactivex.rxkotlin<version>` would make perfect sense.

**Comment by vpriscan** [comment] 2020-03-21 14:46
RxKotlin 3.0.0 is released with package changed to **io.reactivex.rxjava3.kotlin**. We apologize to RxKotlin 3.0.0-RC1 users for inconvenience caused by the change.

**Closed as completed by vpriscan** 2020-03-21 14:46 UTC
